USE [master]
GO

/****** Object:  Database [teste 4040]    Script Date: 25/12/2023 19:54:38 ******/
CREATE DATABASE [teste 4040]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'teste 4040', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\teste 4040.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'teste 4040_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\teste 4040_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [teste 4040].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [teste 4040] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [teste 4040] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [teste 4040] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [teste 4040] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [teste 4040] SET ARITHABORT OFF 
GO

ALTER DATABASE [teste 4040] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [teste 4040] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [teste 4040] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [teste 4040] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [teste 4040] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [teste 4040] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [teste 4040] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [teste 4040] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [teste 4040] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [teste 4040] SET  DISABLE_BROKER 
GO

ALTER DATABASE [teste 4040] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [teste 4040] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [teste 4040] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [teste 4040] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [teste 4040] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [teste 4040] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [teste 4040] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [teste 4040] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [teste 4040] SET  MULTI_USER 
GO

ALTER DATABASE [teste 4040] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [teste 4040] SET DB_CHAINING OFF 
GO

ALTER DATABASE [teste 4040] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [teste 4040] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [teste 4040] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [teste 4040] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [teste 4040] SET QUERY_STORE = OFF
GO

ALTER DATABASE [teste 4040] SET  READ_WRITE 
GO


